spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://good-day.c9zosefelroz.ap-northeast-2.rds.amazonaws.com:3306/good_day
    username: admin
    password: capstone2022


  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true
