spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/goodday?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: capstone2022


  jpa:
    hibernate:
      ddl-auto: create
